### ISSUE TITLE
Ref not propagating to errors object when resolver is used

### ISSUE THREAD

**Issue by TMUND** [react-hook-form/resolvers#77] opened 2020-11-16 20:05 UTC
Hello `react-hook-form`, 

First of all, thank you for a great form library! However, I am noticing an issue with propagating the ref of the input that threw the error when I use the Joi resolver in my project. 

According to the docs here: https://react-hook-form.com/api#errors I should receive `type`, `types`, `message` and `ref` from the errors object. I have confirmed that this is true when I don't use a resolver and construct my field validation manually like so: 

```
console.log(errors);

<input
  ref={register({ required: 'custom required message' })}
  type="email"
  name="email"
  ...etc.
/>
```
![Screen Shot 2020-11-16 at 11 56 19 AM](https://user-images.githubusercontent.com/10443437/99301846-68036d00-2803-11eb-9534-b2b45ad24c09.png)

...but when I construct my field validations via Joi I only receive the `message` and `type` properties from the `errors` object. My code looks something like this: 

```
const { register, errors } = useForm<FormValues>({
  resolver: joiResolver(validationSchema.current),
});

console.log(errors);

<input
  ref={register}
  type="email"
  name="email"
  ...etc.
/>
```

...and my response looks like this: 
![Screen Shot 2020-11-16 at 11 55 28 AM](https://user-images.githubusercontent.com/10443437/99301624-1955d300-2803-11eb-89ee-c3a87e91efec.png)

How do I ensure that the ref of the input which threw the error comes through in the `useForm` errors object? 

Thanks for your help!

**Comment by bluebill1049** [comment] 2020-11-16 21:37
can you share a CSB? so we can reproduce this?

**Comment by TMUND** [comment] 2020-11-17 01:16
Sure thing, to repro: 

* Visit https://codesandbox.io/s/react-hook-form-ref-bug-lo8sr?file=/src/App.js 
* Click the submit button while field is empty 
* Verify the console.log response only contains `message` and `type`

If you update that code to remove the resolver and manually set the validators via `ref={register({ required: 'foo' })}` you'll see that the response contains the correct `ref`. 

Seems to me like this code could be the culprit but I'm not 100% sure of that: https://github.com/react-hook-form/resolvers/blob/master/src/joi.ts#L23-L42

**Comment by bluebill1049** [comment] 2020-11-17 03:17
Thanks @TMUND looks like right now all the resolver doesn't forward any `ref`, what's your usage like? we can consider to forward the `ref`, or potentially see if others have a similar requirement.

**Comment by TMUND** [comment] 2020-11-17 15:53
No problem @bluebill1049 , I need that `ref` in order to be able to easily create a link to the input field which caused the error in an error summary at the top of the page. 

For example, when a user triggers validation my app displays an error summary at the top of the page which the user is focused on. In order to keep the form a11y compliant I need to have each of the errors in the error summary be a link to the input which caused the error so that users can click/tab + enter to the correct field. Here is what that looks like: 

<img width="803" alt="Screen Shot 2020-11-17 at 7 49 01 AM" src="https://user-images.githubusercontent.com/10443437/99412253-61c7cc00-28a9-11eb-9d33-2016cdace6d0.png">

The `react-hook-form` docs also note that the `ref` should be available on the `error` object with no note about isssues with resolvers. 

I think this would be a great enhancement because having that ref allows us more flexibility in how we can build the UI around error states. If I you point me at the right spot in the code and give me some guidance I'd be happy to submit a PR. 

Cheers!

**Comment by TMUND** [comment] 2020-11-23 16:50
Hi @bluebill1049, wondering if there's been any update on this or whether I should start looking for other solutions?

**Comment by bluebill1049** [comment] 2020-11-23 21:16
@TMUND that's a major change, it will take time for us to get to it. perhaps capture those `ref` at your app-level for now.

**Comment by TMUND** [comment] 2020-11-23 21:34
> @TMUND that's a major change, it will take time for us to get to it. perhaps capture those `ref` at your app-level for now.

Sounds good, are we talking weeks or months in terms of ETA? If I can help move this along in any way please LMK. 

I will weigh timeline vs. implementing my own solution because it seems heavy handed to build custom ref interceptor. Unless you see a straightforward way to access those in the meantime...

**Comment by bluebill1049** [comment] 2020-11-23 21:36
@TMUND I would recommend you go with your own solution for now.

**Comment by TMUND** [comment] 2020-11-23 21:52
> @TMUND I would recommend you go with your own solution for now.

Will do. I recommend updating the `errors` object docs [HERE](https://react-hook-form.com/api#errors) with a note to reflect the issue with `ref`s when using a resolver. It may help others with debugging...

![react-hook-form-docs-11-23-20](https://user-images.githubusercontent.com/10443437/100019451-ebd4d080-2d92-11eb-9a7b-310c99ef0f9d.png)

**Comment by jorisre** [comment] 2021-02-03 22:07
Hey @TMUND 👋🏻 

The [v2.0.0-beta.10](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0-beta.10) with ref is available ! 

```sh
yarn add @hookform/resolvers@beta
```

**Comment by TMUND** [comment] 2021-02-03 22:45
OMG @jorisre, amazing! Thank you 🙏

**Comment by jorisre** [comment] 2021-04-02 17:09
Closing, [V2 released](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0) 🎉

**Closed by jorisre** 2021-04-02 17:09 UTC
Labels: enhancement
