### ISSUE TITLE
NextJs 12: Named export `set` not found

### ISSUE THREAD

**Issue by mrodrigues95** [react-hook-form/resolvers#271] opened 2021-10-31 19:21 UTC
**Describe the bug**
I've upgraded to NextJS v12 which [supports](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports) ES modules out of the box and now I'm getting the following error whenever I try to load any page that imports uses `zodResolver`.

```
file:///node_modules/@hookform/resolvers/dist/resolvers.mjs:1
import{get as r,set as o}from"react-hook-form";var a=function(a,e){var f={};for(var t in a){var n=r(e,t);o(f,t,Object.assign(a[t],{ref:n&&n.ref}))}return f};export{a as toNestError};
error - unhandledRejection: SyntaxError: Named export 'set' not found. The requested module 'react-hook-form' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-hook-form';
const {get: r,set: o}from"react-hook-form";var a=function(a,e){var f={};for(var t in a){var n=r(e,t);o(f,t,Object.assign(a[t],{ref:n&&n.ref}))}return f};export{a: toNestError} = pkg;
```

**To Reproduce**
1. Create a new NextJS project on v12
2. Install `@hookform/resolvers`
3. Try to use any resolver (e.g. zod)

```
import { zodResolver } from '@hookform/resolvers/zod';

export const useZodForm = ({
  schema,
  ...formConfig
}) => {
  return useForm({
    ...formConfig,
    resolver: zodResolver(schema),
  });
};
```

**Expected behavior**
Import is resolved.

**Additional context**
`"@hookform/resolvers": "^2.8.2"`, `"react-hook-form": "^7.18.0"`, `"next": "^12.0.2"`.

**Comment by allwd** [comment] 2021-10-31 21:16
@mrodrigues95 
I faced the same issue just now. Fixed it temporarily by replacing `import { yupResolver } from '@hookform/resolvers/yup';` with `import { yupResolver } from '@hookform/resolvers/yup/dist/yup.umd';`. Maybe it's going to work for you as well.

**Comment by mrodrigues95** [comment] 2021-10-31 21:47
@allwd That seems to work as a work around for the time being, thanks.

**Comment by jhg023** [comment] 2021-11-01 00:46
I'm facing this bug as well after updating to Nextjs 12.0.2, and I did not encounter this issue on Nextjs 12.0.1

**Comment by Czer0C** [comment] 2021-11-01 01:22
Having the same issue with NextJS **12.0.2**, the temporary fix provided by @allwd works.

**Comment by sgonv** [comment] 2021-11-01 10:27
How about Typescript? I tried @allwd 's suggestion, but it doesn't work well.

```
Type error: Could not find a declaration file for module '@hookform/resolvers/yup/dist/yup.umd'.
'/path/to/my_project/node_modules/@hookform/resolvers/yup/dist/yup.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hookform__resolvers` if it exists or add a new declaration (.d.ts) file containing `declare module '@hookform/resolvers/yup/dist/yup.umd';`
```

**Comment by azarmehri** [comment] 2021-11-01 15:55
Hi @sgonv. For Typescript, you need to import resolver like `import { zodResolver } from '@hookform/resolvers/zod/dist/zod'` instead `@hookform/resolvers/zod`. It works for me 😊

**Comment by bluebill1049** [comment] 2021-11-01 22:11
thanks @jorisre 🙏

**Comment by sgonv** [comment] 2021-11-02 02:23
@azarmehri Oh, it worked for me. Thanks!

**Comment by hongdeyuan** [comment] 2021-11-02 07:40
This is a way to bypass the Rust compiler and does not solve the fundamental problem. If you install a dependency that does not satisfy the CommonJS module, the project will still not run properly

**Comment by uDaniAlves** [comment] 2021-11-02 17:47
I'm having the same issue and @allwd solution worked from me but Storybook stopped working.

The errors are:
`ERROR in ./node_modules/@hookform/resolvers/yup/dist/yup.mjs 1:909-910
Can't import the named export 'appendErrors' from non EcmaScript module (only default export is available)`

`ERROR in ./node_modules/@hookform/resolvers/yup/dist/yup.mjs 1:710-711
Can't import the named export 'toNestError' from non EcmaScript module (only default export is available)`

`ERROR in ./node_modules/@hookform/resolvers/yup/dist/yup.mjs 1:582-583
Can't import the named export 'validateFieldsNatively' from non EcmaScript module (only default export is available)`

**Comment by Yhozen** [comment] 2021-11-02 19:00
Another fix would be 

```ts
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { yupResolver } = require('@hookform/resolvers/yup')
```

**Comment by JamesWong1999** [comment] 2021-11-03 00:20
similar issue: https://github.com/vercel/next.js/issues/30750 ?

**Comment by PaulHaze** [comment] 2021-11-03 23:46
Facing the same issue, tried @allwd  & @Yhozen solutions. Neither worked
```


10:44:06.116 | > Build error occurred
-- | --
10:44:06.117 | file:///vercel/path0/node_modules/@hookform/resolvers/dist/resolvers.mjs:1
10:44:06.117 | import{get  as r,set as e}from"react-hook-form";var i=function(e,i){for(var a in  i.fields){var  f=i.fields[a];if(f&&f.ref&&"reportValidity"in f.ref){var   t=r(e,a);f.ref.setCustomValidity(t&&t.message\|\|""),f.ref.reportValidity()}}},a=function(a,f){f.shouldUseNativeValidation&&i(a,f);var  t={};for(var o in a){var  s=r(f.fields,o);e(t,o,Object.assign(a[o],{ref:s&&s.ref}))}return  t};export{a as toNestError,i as validateFieldsNatively};
10:44:06.118 | ^^^
10:44:06.118 | SyntaxError:  Named export 'set' not found. The requested module 'react-hook-form' is  a CommonJS module, which may not support all module.exports as named  exports.
```

If anyone has any other solutions I would love to hear them!

**Comment by dsacramone** [comment] 2021-11-04 00:59
Same issue. No solutions presented here works.

**These did not work:**
import { yupResolver } from '@hookform/resolvers/yup/dist/yup.umd';
const { yupResolver } = require('@hookform/resolvers/yup');
import { yupResolver } from '@hookform/resolvers/yup/dist/yup';

Any other solutions?

**Comment by PaulHaze** [comment] 2021-11-04 03:34
> Same issue. No solutions presented here works.
> 
> **These did not work:** import { yupResolver } from '@hookform/resolvers/yup/dist/yup.umd'; const { yupResolver } = require('@hookform/resolvers/yup'); import { yupResolver } from '@hookform/resolvers/yup/dist/yup';
> 
> Any other solutions?
> 
> @jorisre - any updates to report?

@dsacramone Whilst not ideal, you can see my reply above in that dropping the version of Next down to 12.0.1 (specifically) in package.json and then re-running yarn (or npm) fixed all the build issues for me. As others have linked, this thread over at the Next repo seems to be dealing with the same (or similar) problem:
https://github.com/vercel/next.js/issues/30750

**Comment by bluebill1049** [comment] 2021-11-04 03:47
can we try nextjs `v12.0.3-canary.2`? see if this issue is getting resolved?

**Comment by PaulHaze** [comment] 2021-11-04 06:54
> can we try nextjs `v12.0.3-canary.2`? see if this issue is getting resolved?

I actually tried that version before reverting back to 12.0.1 and from what I could tell on my end it didn't do anything to resolve it. I tried the 3 methods of importing  that @allwd  & @Yhozen mentioned.

**Comment by dsacramone** [comment] 2021-11-05 05:10
> Facing the same issue with Next Js, tried @allwd & @Yhozen solutions. Neither worked
> 
> ```
> 
> 
> 10:44:06.116 | > Build error occurred
> -- | --
> 10:44:06.117 | file:///vercel/path0/node_modules/@hookform/resolvers/dist/resolvers.mjs:1
> 10:44:06.117 | import{get  as r,set as e}from"react-hook-form";var i=function(e,i){for(var a in  i.fields){var  f=i.fields[a];if(f&&f.ref&&"reportValidity"in f.ref){var   t=r(e,a);f.ref.setCustomValidity(t&&t.message\|\|""),f.ref.reportValidity()}}},a=function(a,f){f.shouldUseNativeValidation&&i(a,f);var  t={};for(var o in a){var  s=r(f.fields,o);e(t,o,Object.assign(a[o],{ref:s&&s.ref}))}return  t};export{a as toNestError,i as validateFieldsNatively};
> 10:44:06.118 | ^^^
> 10:44:06.118 | SyntaxError:  Named export 'set' not found. The requested module 'react-hook-form' is  a CommonJS module, which may not support all module.exports as named  exports.
> ```
> 
> If anyone has any other solutions I would love to hear them!
> 
> EDIT Next.Js versions 11.1.3 and 12.0.1 have fixed the build issue so at least it building for now....

Hey @PaulHaze , are you still importing it the same? I did as you suggest and am using 12.0.1, and it did build, but when viewed in a browser, the page doesn't work - as expected if my hookform isn't working. Did you use a special "import" or way to get at it?

**Comment by jhg023** [comment] 2021-11-06 21:38
Nextjs 12.0.3 was released, but it doesn't resolve this issue, unfortunately.

**Comment by bigint** [comment] 2021-11-07 02:46
Yes still this is blocking 😕

**Comment by phanvanluan94** [comment] 2021-11-07 05:41
Same issue.

**Comment by jeromeSH26** [comment] 2021-11-08 16:28
downgrading to 12.0.1 fix the issue

**Comment by PaulHaze** [comment] 2021-11-08 20:20
> Hey @PaulHaze , are you still importing it the same? I did as you suggest and am using 12.0.1, and it did build, but when viewed in a browser, the page doesn't work - as expected if my hookform isn't working. Did you use a special "import" or way to get at it?
> 
> my error is:
> ## excludeEmptyString is not defined

@dsacramone No I think I am just importing it as usual:

`import { yupResolver } from '@hookform/resolvers/yup';`

That is what I am using to import it. The versions I have in my package.json are:

` "@hookform/resolvers": "^2.8.3",`
`"next": "12.0.1",`

So far it is working both locally and when I build/deploy it. I hope that is of some use !? :)

**Comment by justyn-clark** [comment] 2021-11-10 01:54
`import { yupResolver } from '@hookform/resolvers/yup/dist/yup'` worked for me

**Comment by taskordhq** [comment] 2021-11-10 04:32
Thanks @justyn-clark as a temp workaround this works

`import { zodResolver } from '@hookform/resolvers/zod/dist/zod'`

**Comment by dsacramone** [comment] 2021-11-10 21:12
> > Hey @PaulHaze , are you still importing it the same? I did as you suggest and am using 12.0.1, and it did build, but when viewed in a browser, the page doesn't work - as expected if my hookform isn't working. Did you use a special "import" or way to get at it?
> > my error is:
> > ## excludeEmptyString is not defined
> 
> @dsacramone No I think I am just importing it as usual:
> 
> `import { yupResolver } from '@hookform/resolvers/yup';`
> 
> That is what I am using to import it. The versions I have in my package.json are:
> 
> ` "@hookform/resolvers": "^2.8.3",` `"next": "12.0.1",`
> 
> So far it is working both locally and when I build/deploy it. I hope that is of some use !? :)

Hey Paul, what version of react-hook-form are you using, as I have those same versions you mentioned (next/hookform) and still getting the error. 

> > Hey @PaulHaze , are you still importing it the same? I did as you suggest and am using 12.0.1, and it did build, but when viewed in a browser, the page doesn't work - as expected if my hookform isn't working. Did you use a special "import" or way to get at it?
> > my error is:
> > ## excludeEmptyString is not defined
> 
> @dsacramone No I think I am just importing it as usual:
> 
> `import { yupResolver } from '@hookform/resolvers/yup';`
> 
> That is what I am using to import it. The versions I have in my package.json are:
> 
> ` "@hookform/resolvers": "^2.8.3",` `"next": "12.0.1",`
> 
> So far it is working both locally and when I build/deploy it. I hope that is of some use !? :)

Thanks! What version of **react-hook-form** are you using?

**Comment by PaulHaze** [comment] 2021-11-15 05:33
@dsacramone I'm using  "react-hook-form": "^7.18.1",

**Comment by jhg023** [comment] 2021-11-16 01:25
Next.js 12.0.4 didn't solve this issue either.

**Comment by yordis** [comment] 2021-11-18 05:37
> `import { yupResolver } from '@hookform/resolvers/yup/dist/yup'` worked for me

Didn't work for me, any updates on this one?

**Comment by ItaloCanturil** [comment] 2021-11-18 12:57
> 
> 
> > `import { yupResolver } from '@hookform/resolvers/yup/dist/yup'` worked for me
> 
> Didn't work for me, any updates on this one?

`const { yupResolver } = require('@hookform/resolvers/yup')` worked for me

**Comment by Seijinx** [comment] 2021-11-19 03:09
Upgrading "react-hook-form" to "7.20.0" generates the same issue in Next 11. I'm freezing this at 7.19.5 for now.

**Comment by bigint** [comment] 2021-11-19 04:49
For me 7.20.0 with next 12.0.4 works fine 🎉

**Comment by bluebill1049** [comment] 2021-11-19 22:34
7.20.0 type module breaks other libs depends on it...

**Comment by yordis** [comment] 2021-11-19 23:01
Python 2 vs. 3 ....

@bluebill1049 I think we should commit to figuring out how to make it work for ESM ... I know it is painful, but this was the inevitable from NodeJS 😭

**Comment by bluebill1049** [comment] 2021-11-19 23:03
@yordis we do have ESM support (as far as I know), its' a mix with commonJS and ESM the real pain.

**Comment by yordis** [comment] 2021-11-19 23:22
@bluebill1049 yeah I checked the implementation and it seems like ... but I hear you ... I am still try-and-error with setups because we are under the mercy of how the underline tools originally load the components.

And, I think, unless the Node version supports the `package.json#exports` it wouldn't work, which I am not sure if Vercel `NodeJS@14` supports it.

**Comment by newadbie** [comment] 2021-11-22 08:00
Some news? I still get this issue, it is 20 day :o

**Comment by bluebill1049** [comment] 2021-11-22 09:29
thanks, @yordis for trying to help.

**Comment by bluebill1049** [comment] 2021-11-22 10:03
This is likely not an issue with `react-hook-form` as the module itself does provide ESM entry point: https://www.skypack.dev/view/react-hook-form

**Comment by Seijinx** [comment] 2021-11-23 02:29
> Upgrading "react-hook-form" to "7.20.0" generates the same issue in Next 11.1.2. I'm freezing this at 7.19.5 for now.

`react-hook-form` 7.20.2 fix this same problem in Next 11.1.2. Thanks @bluebill1049 !

**Comment by jhg023** [comment] 2021-11-23 02:30
I can't update to `v7.20.2` when using `v12.0.4` of Next.js, as I experience the same issue as the OP. The latest version of `react-hook-form` I can use is `v7.20.1`.

**Comment by novazembla** [comment] 2021-11-24 17:12
I also can confirm that `v7.20.2` in combination with next `v12.0.4` does not compile, but `v.7.20.1` does. Just want to add that I added some `webpack` related settings `next.config.js`. So in my case next does not compile with webpack.

**Comment by AlexandruCalinica** [comment] 2021-11-29 06:21
`v7.20.1` works with `v12.0.2` for me.

**Comment by embedvr** [comment] 2021-11-29 22:29
> Another fix would be
> 
> ```ts
> // eslint-disable-next-line @typescript-eslint/no-var-requires
> const { yupResolver } = require('@hookform/resolvers/yup')
> ```

This fixed seems to have fixed it for me. The fix from @allwd didn't though.

**Comment by mario-jerkovic** [comment] 2021-12-04 13:59
`import { yupResolver } from '@hookform/resolvers/zod/dist/zod'` worked for me with next `12.0.6` with deprecation warning in console 
```
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/projectsName/node_modules/@hookform/resolvers/package.json.
Update this package.json to use a subpath pattern like "./*".
```

NodeJS Version `16.13.1`

**Comment by pronovaso** [comment] 2021-12-04 17:21
I still have an issue with yup. My setup is last versions of resolver,react-hook-form and NextJS version from 12.0.2 to 12.0.6

**Comment by AloisCRR** [comment] 2021-12-05 14:53
Hello, I'm getting this error:

```
Server Error
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

I've tried all ways, the only one that works is using `require()` but then I loose TypeScript inference and the linter goes crazy (I mean it forbids the use of require()). If I remove the "resolver" property from `useForm` then everything works properly.

Versions:
```
"@hookform/resolvers": "^2.8.4"
"next": "^12.0.7"
"react-hook-form": "^7.20.5"
```
Node `v17.2.0`

**Comment by horaotoko** [comment] 2021-12-06 10:01
Adding `experimental.esmExternals: false` to next.config file works for me.

https://github.com/vercel/next.js/issues/30750#issuecomment-962198711

**Comment by daniel-stockman-lark** [comment] 2021-12-08 19:02
Using [patch-package](https://github.com/ds300/patch-package), this fixed it for me (with react-hook-form@7.21.0):

```diff
diff --git a/node_modules/react-hook-form/dist/index.esm.js b/node_modules/react-hook-form/dist/index.mjs
similarity index 100%
rename from node_modules/react-hook-form/dist/index.esm.js
rename to node_modules/react-hook-form/dist/index.mjs
diff --git a/node_modules/react-hook-form/package.json b/node_modules/react-hook-form/package.json
index 579ab00..1e1c18e 100644
--- a/node_modules/react-hook-form/package.json
+++ b/node_modules/react-hook-form/package.json
@@ -3,11 +3,11 @@
   "description": "Performant, flexible and extensible forms library for React Hooks",
   "version": "7.21.0",
   "main": "dist/index.cjs.js",
-  "module": "dist/index.esm.js",
+  "module": "dist/index.mjs",
   "umd:main": "dist/index.umd.js",
   "unpkg": "dist/index.umd.js",
   "jsdelivr": "dist/index.umd.js",
-  "jsnext:main": "dist/index.esm.js",
+  "jsnext:main": "dist/index.mjs",
   "source": "src/index.ts",
   "types": "dist/index.d.ts",
   "sideEffects": true,
@@ -18,7 +18,7 @@
   "exports": {
     "./package.json": "./package.json",
     ".": {
-      "import": "./dist/index.esm.js",
+      "import": "./dist/index.mjs",
       "require": "./dist/index.cjs.js"
     }
   },
```

Basically, the import target needs to use the `.mjs` extension, _preserving_ the default `type` of CommonJS for the overall package.

**Comment by hongdeyuan** [comment] 2021-12-08 19:02
本人已收到您的邮件，辛苦了！如有重要事情，看到后，将尽快给你回复。。。

**Comment by bluebill1049** [comment] 2021-12-08 22:22
> Using [patch-package](https://github.com/ds300/patch-package), this fixed it for me (with react-hook-form@7.21.0):
> 
> ```diff
> diff --git a/node_modules/react-hook-form/dist/index.esm.js b/node_modules/react-hook-form/dist/index.mjs
> similarity index 100%
> rename from node_modules/react-hook-form/dist/index.esm.js
> rename to node_modules/react-hook-form/dist/index.mjs
> diff --git a/node_modules/react-hook-form/package.json b/node_modules/react-hook-form/package.json
> index 579ab00..1e1c18e 100644
> --- a/node_modules/react-hook-form/package.json
> +++ b/node_modules/react-hook-form/package.json
> @@ -3,11 +3,11 @@
>    "description": "Performant, flexible and extensible forms library for React Hooks",
>    "version": "7.21.0",
>    "main": "dist/index.cjs.js",
> -  "module": "dist/index.esm.js",
> +  "module": "dist/index.mjs",
>    "umd:main": "dist/index.umd.js",
>    "unpkg": "dist/index.umd.js",
>    "jsdelivr": "dist/index.umd.js",
> -  "jsnext:main": "dist/index.esm.js",
> +  "jsnext:main": "dist/index.mjs",
>    "source": "src/index.ts",
>    "types": "dist/index.d.ts",
>    "sideEffects": true,
> @@ -18,7 +18,7 @@
>    "exports": {
>      "./package.json": "./package.json",
>      ".": {
> -      "import": "./dist/index.esm.js",
> +      "import": "./dist/index.mjs",
>        "require": "./dist/index.cjs.js"
>      }
>    },
> ```
> 
> Basically, the import target needs to use the `.mjs` extension, _preserving_ the default `type` of CommonJS for the overall package.

thank you so much for your contribution and help! will release a beta on this soon.

**Comment by bluebill1049** [comment] 2021-12-09 01:58
can we test this beta version? `react-hook-form@7.21.1-0`

**Comment by jorisre** [comment] 2021-12-09 13:44
Seems working for me @bluebill1049 👏🏻

**Comment by evocateur** [comment] 2021-12-09 17:15
@bluebill1049 `react-hook-form@7.21.1-0` works with `next@12.0.7`, thanks!

**Comment by AndysonDK** [comment] 2021-12-09 17:59
Hmm I'm getting the following error when using react-hook-form with storybook, it does work with next.js now!:
```
ERROR in /home/anders/Projects/syncbase/node_modules/react-hook-form/dist/index.esm.mjs 68:24-43
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
```

These are the versions that I'm currently using:
```JSON
"@hookform/resolvers": "^2.8.4",
"react-hook-form": "7.21.1-0",
"@storybook/addon-a11y": "^6.4.9",
"@storybook/addon-essentials": "^6.4.9",
"@storybook/addon-interactions": "^6.4.9",
"@storybook/addon-postcss": "^2.0.0",
"@storybook/jest": "^0.0.5",
"@storybook/react": "^6.4.9",
"@storybook/testing-library": "^0.0.7"
```:

Should I make a new dedicated issue for this?

**Comment by dsacramone** [comment] 2021-12-10 02:44
> 7.21.1-0

did you run into an issue like this?

```
npm ERR! Could not resolve dependency:
npm ERR! peer react-hook-form@"^7.0.0" from @hookform/resolvers@2.8.4
npm ERR! node_modules/@hookform/resolvers
npm ERR!   @hookform/resolvers@"^2.8.3" from the root project

```

**Comment by bluebill1049** [comment] 2021-12-10 06:49
closing: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.21.1

**Comment by bluebill1049** [comment] 2021-12-10 08:21
Sorry, this is a never-ending issue... https://github.com/react-hook-form/react-hook-form/issues/7251

**Comment by yordis** [comment] 2021-12-10 08:23
@bluebill1049 that one is on CRA ... they are way behind updating anything being honest on the topic ... but I hear you ... this Python 2v3 situation is really frustrating

**Comment by bluebill1049** [comment] 2021-12-10 08:28
Thanks for understanding @yordis... 🤦🏻‍♂️

**Comment by yordis** [comment] 2021-12-10 08:31
@bluebill1049 what could be happening could be

A) The NodeJS version itself doesn't support the `exports` and ESM by default (pre-v14 I think)
B) CRA setup tooling doesn't support the `exports` neither

So ... I would suggest to ask in CRA if they support the `exports` (dual package) before getting into a rabbit hole.

**Comment by bluebill1049** [comment] 2021-12-10 08:45
Honestly, I think CRA users shouldn't expect a breaking change so does nextjs, however, this issue is created by nextjs 12, so to be fair, I hope the nextjs team can look into a solution for fixing this. In the meantime, I think it's better to have a solution to comfort both parties without destroying the developer experience (on whatever users prefer to use).

**Comment by yordis** [comment] 2021-12-10 08:50
@bluebill1049 and that is why I mentioned to you a few weeks ago that I gave up on ESM unless I have a strong reason ...

The tools are still figuring out how to deal with it ... especially those that are not Webpack since it was doing a lot of magical things.

Not sure what is the right resolution here ... technically blame Webpack for some of the mess since it trained people to get used to "wrong things" (kind of misleading word but close enough, I cant find a better word).

Anyway ... back to broken NextJS on my side .... which is really annoying, I stopped using CRA in 2018 for a reason ... (before I even adopted NextJS) that is all I will say.

**Comment by yordis** [comment] 2021-12-10 08:54
```
"react-hook-form": "7.21.1",
```

Had to lock the version to `7.21.1` for now at least

**Comment by bluebill1049** [comment] 2021-12-10 08:57
all valid opinions @yordis

**Comment by pronovaso** [comment] 2021-12-10 09:18
I confirm, that version 7.21.1 and Next 12.0.7 works well. 7.21.1. Thanks a lot.

**Comment by simontaisne** [comment] 2021-12-10 10:13
`7.21.1` works well, but not `7.21.2` 😅

**Comment by evocateur** [comment] 2021-12-10 17:42
I believe the root cause for the CRA issue is that RHF uses the `import * as React from 'react'` form when it should be using `import React from 'react'`. React itself is not ESM, it's just a default export that Babel et al make-believe is a series of named exports, thus the error message.

I'm surprised RHF isn't using `esModuleInterop: true` in its tsconfig. Digging in locally to see if my hunch bears fruit.

**Comment by sveggiani** [comment] 2021-12-10 18:09
For me neither `7.21.1` or `7.21.2` are working with Next.js `12.0.7`.

**Comment by evocateur** [comment] 2021-12-10 19:13
I verified that https://github.com/react-hook-form/react-hook-form/pull/7261 works for NextJS 12.0.7, but I don't have a Storybook or CRA project offhand to test the backward-compatibility.

**Comment by bluebill1049** [comment] 2021-12-10 22:06
thank you again @evocateur

**Comment by bluebill1049** [comment] 2021-12-11 09:06
beta: `Version 7.21.3-beta.0`

**Comment by bluebill1049** [comment] 2021-12-11 09:14
the above beta pass test for my with CRA and nextjs thank so much @evocateur life saver.

**Comment by JuanM04** [comment] 2021-12-11 14:18
v7.21.3-beta.0 works perfectly!

**Comment by bluebill1049** [comment] 2021-12-12 01:01
oh wow, I didn't check evocateur's profile, he is the creator/author of [Lerna](https://github.com/lerna/lerna). Respect 🎩

**Comment by Alexandredc** [comment] 2021-12-13 07:39
Many thanks @bluebill1049 & @evocateur  🙏

**Comment by bluebill1049** [comment] 2021-12-13 07:44
thanks @Alexandredc All effort and credit goes to evocateur ❤️

**Comment by evocateur** [comment] 2021-12-13 17:12
@bluebill1049 I'm merely the longtime maintainer (presently a bit delinquent), not the author, of Lerna. I appreciate your responsiveness and effort as creator and maintainer of React Hook Form!

**Comment by bluebill1049** [comment] 2021-12-13 21:37
hopefully, this is the last time i close this issue: https://github.com/react-hook-form/react-hook-form/releases/tag/v7.22.0 🙏

**Closed by bluebill1049** 2021-12-13 21:37 UTC
Labels: help wanted, dependencies

**Comment by ayepRahman** [comment] 2022-11-19 08:28
This reoccur in next js v13 when I am trying to use zodResolver


```
 "dependencies": {
    "@heroicons/react": "^2.0.13",
    "@hookform/error-message": "^2.0.1",
    "@hookform/resolvers": "^2.9.10",
    "@tanstack/react-query": "^4.16.1",
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "aws-sdk": "^2.1257.0",
    "axios": "^1.1.3",
    "clsx": "^1.2.1",
    "dotenv": "^16.0.3",
    "eslint": "8.27.0",
    "eslint-config-next": "^13.0.3",
    "flowbite": "^1.5.4",
    "flowbite-react": "^0.3.5",
    "mongodb": "^4.11.0",
    "multer": "^1.4.5-lts.1",
    "next": "^13.0.3",
    "next-connect": "^0.13.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.3",
    "react-hook-form": "^7.39.4",
    "react-tailwindcss-select": "^1.3.3",
    "typescript": "4.9.3",
    "zod": "^3.19.1"
  },
```



```shell
ReferenceError: File is not defined
    at 3608 (/Users/arifrahman/Code/personal/pokedex-nextjs13/.next/server/app/pokemon/create/page.js:412:31)
    at __webpack_require__ (/Users/arifrahman/Code/personal/pokedex-nextjs13/.next/server/webpack-runtime.js:25:42)
    at B (/Users/arifrahman/Code/personal/pokedex-nextjs13/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:924:142)
    at H (/Users/arifrahman/Code/personal/pokedex-nextjs13/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:922:264)
    at /Users/arifrahman/Code/personal/pokedex-nextjs13/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:927:218

```

**Comment by Junnygram** [comment] 2023-09-11 14:58
how do i fix the error in my next13 app
Type 'Resolver<{ password?: string | undefined; email: string; }>' is not assignable to type 'Resolver<LoginModel, any>'.
  Types of parameters 'values' and 'values' are incompatible.
    Type 'LoginModel' is not assignable to type '{ password?: string | undefined; email: string; }'

`
export type LoginModel = {
  email?: string;
  password?: string;
};
`
`  const {
    handleSubmit,
    register,
    formState: { errors, isSubmitting, isValid },
  } = useForm<LoginModel>({
    resolver: yupResolver(schema),
    mode: 'all',
  });`


`const schema = yup.object().shape({
  email: yup.string().email().required(),
  password: yup.string().password(),
});
`

**Comment by hongdeyuan** [comment] 2023-09-11 14:58
I have received your email, thank you!If there is anything important, I will reply to you as soon as I see it...

**Comment by Junnygram** [comment] 2023-09-12 08:18
its been fixed , i just had to through the documentation well 
`const schema = yup.object().shape({
  email: yup.string().email().required(),
  password: yup.string().password().required(),
});`

for the type
`export type LoginModel = {
  email: string;
  password: string;
};
`
