### ISSUE TITLE
Error when Trying to Use Arktype Resolver

### ISSUE THREAD

**Issue by lucaschultz** [react-hook-form/resolvers#693] opened 2024-06-18 10:33 UTC
**Describe the bug**
When trying to use the `arktypeResolver` the following error happens:

> Error: Tried to initialize an $ark registry but one already existed.
This probably means you are either depending on multiple versions of an arktype package,
or importing the same package from both ESM and CJS.
Review package.json versions across your repo to ensure consistency.

**To Reproduce**

1. Call the `useForm` hook with the `arktypeResolver` as `resolver`.

**Codesandbox link (Required)**
No Codesandbox link, but I created a [minimal reproduction using Next.js here](https://github.com/lucaschultz/arktype-resolver-bug), but the error happened in a Vite/React app I'm working on. @ssalbdivad you might wanna have a look 😊

**Expected behavior**
Being able to use the provider, regardless if the project is ESM or not.

**Screenshots**

<img width="1077" alt="Bildschirmfoto 2024-06-18 um 12 28 05" src="https://github.com/react-hook-form/resolvers/assets/45899273/6b1020ae-4b87-4126-a609-69d7c494c43f">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 125.0.6422.114

**Comment by ssalbdivad** [comment] 2024-06-18 13:58
Thanks for letting me know! This issue should be opened in the [ArkType repo](https://github.com/arktypeio/arktype/issues/new?assignees=ssalbdivad&labels=bug&projects=&template=bug_report.md&title=) instead.

Happy to investigate what might be going wrong there!

**Comment by lucaschultz** [comment] 2024-06-19 19:46
> This issue should be opened in the [ArkType repo](https://github.com/arktypeio/arktype/issues/new?assignees=ssalbdivad&labels=bug&projects=&template=bug_report.md&title=) instead.

@ssalbdivad ah yes, I was wondering where to open the issue. Settled on this repository because the error message lead to be believe the issue might be that using the resolver creates another registry which somehow collides with the other one, so I assumed the problem might be one of the resolver rather than with Arktype itself.

Should I open a copy in the Arktype repo?

**Comment by jorisre** [comment] 2024-07-02 20:51
Closing in favor fo https://github.com/arktypeio/arktype/issues/1022

**Comment by jorisre** [comment] 2024-07-02 20:58
I made some changes to improve bundle size in [#699](https://github.com/react-hook-form/resolvers/pull/699/files#diff-58dd8ff456c7458f7171eb32c22adb56787c55dc0ef0d43778110489bbc01dc1)Hopefully, it will fix this issue in the next release.

**Comment by jorisre** [comment] 2024-07-05 10:13
@lucaschultz Can you try with the last version (3.8.0)?

**Comment by jorisre** [comment] 2024-07-06 04:50
I looked at the example you provided to reproduce the issue in Next.js and updated the `@hookform/resolvers` package to its latest version (3.9.0). The problem is now fixed. Thank you for reporting the issue. I'm closing this issue since it's been resolved.

**Closed by jorisre** 2024-07-06 04:50 UTC
