### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by prantaDutta** [react-hook-form/resolvers#107] opened 2021-01-05 10:26 UTC
Hi, I am having this issue suddenly. I don't know where this came from. My code was working last night but now I am having this error. 
```
Server Error
SyntaxError: Cannot use import statement outside a module
```
![Screenshot](https://user-images.githubusercontent.com/44747303/103635131-46f10a00-4f72-11eb-9a7a-b15908388882.png)
This is my code...
```
const { register, handleSubmit, errors, setError } = useForm<LoginFormValues>(
    {
      resolver: yupResolver(loginValidationSchema),
      mode: "onTouched",
      reValidateMode: "onBlur",
    }
  );
```
Inside the form:
```
<form className="mt-10" onSubmit={handleSubmit(onSubmit)}>
            <InputTextField
              type="email"
              name="email"
              label="Email Address"
              error={errors.email?.message}
              placeholder="youremail@email.com"
              register={register}
            />
            <div className="mt-6">
              <InputTextField
                type="password"
                name="password"
                label="Password"
                error={errors.password?.message}
                placeholder="Enter Your Password"
                register={register}
              />
            </div>

            <div className="mt-6">
              <button type="submit"
              >
                Log In
              </button>
            </div>
          </form>
```
I can't recreate this error in the code sandbox. It's showing me some other errors. I am so confused right now. BTW,  I am using nextjs with typescript

**Comment by bluebill1049** [comment] 2021-01-05 10:27
which version are you using?

**Comment by prantaDutta** [comment] 2021-01-05 10:33
"@hookform/resolvers": "^1.3.2",
"react-hook-form": "^6.14.0",

**Comment by prantaDutta** [comment] 2021-01-05 10:34
Check out this branch: https://github.com/prantaDutta/final-project/tree/using-fauna-db

**Comment by prantaDutta** [comment] 2021-01-05 10:56
Hi, It's probably a bug in your latest release. Because I installed the beta version of this package and it's working fine.

**Comment by callamwilliams** [comment] 2021-01-05 11:15
Yep same issue

**Comment by prumand** [comment] 2021-01-05 11:53
I have the same issue. Downgrading to `1.3.0` worked for me. Seems to be a duplicate of https://github.com/react-hook-form/resolvers/issues/100

**Comment by jorisre** [comment] 2021-01-05 11:58
Same issue as https://github.com/react-hook-form/resolvers/issues/100

**Closed by jorisre** 2021-01-05 11:58 UTC
Labels: Need more detail

**Comment by mskarimi** [comment] 2021-02-20 11:41
same issue

import { transformToNestObject } from 'react-hook-form';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/mohamad/Android/Projects/Website/ismv-website/node_modules/@hookform/resolvers/yup.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)


"@hookform/resolvers": "^1.3.4",
"react-hook-form": "^6.15.2",

**Comment by jorisre** [comment] 2021-02-20 21:47
@mskarimi Please have a look to https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998
