### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by batamire** [react-hook-form/resolvers#71] opened 2020-11-05 10:50 UTC
trying to:
```
import { zodResolver } from "@hookform/resolvers/zod";
```

gives me:

```
Uncaught ReferenceError: exports is not defined
    at Module../node_modules/@hookform/resolvers/dist/zod.js (zod.js:11)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object../node_modules/@hookform/resolvers/zod.js (zod.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    ...
```

This is a Rails webpacker + typescript app.

**Comment by bluebill1049** [comment] 2020-11-05 10:53
more detail... which version and etc... can you reproduce that in CSB?

**Comment by batamire** [comment] 2020-11-05 10:59
`@hookform/resolvers": "^1.0.0"`

I'm afraid I cannot reproduce it as this is a large Rails app with TypeScript React and GraphQL. Could it be the way you export modules? I really lack JS packaging knowledge...

my babel.config.js:
```
module.exports = function(api) {
  var validEnv = ["development", "test", "production"];
  var currentEnv = api.env();
  var isDevelopmentEnv = api.env("development");
  var isProductionEnv = api.env("production");
  var isTestEnv = api.env("test");

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      "Please specify a valid `NODE_ENV` or " +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        "."
    );
  }

  return {
    presets: [
      isTestEnv && [
        "@babel/preset-env",
        {
          targets: {
            node: "current"
          },
          modules: "commonjs"
        },
        "@babel/preset-react"
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        "@babel/preset-env",
        {
          forceAllTransforms: true,
          useBuiltIns: "entry",
          corejs: 3,
          modules: false,
          exclude: ["transform-typeof-symbol"]
        }
      ],
      [
        "@babel/preset-react",
        {
          development: isDevelopmentEnv || isTestEnv,
          useBuiltIns: true
        }
      ],
      ['@babel/preset-typescript', { 'allExtensions': true, 'isTSX': true }]
    ].filter(Boolean),
    plugins: [
      "babel-plugin-macros",
      "@babel/plugin-syntax-dynamic-import",
      isTestEnv && "babel-plugin-dynamic-import-node",
      "@babel/plugin-transform-destructuring",
      [
        "@babel/plugin-proposal-class-properties",
        {
          loose: true
        }
      ],
      [
        "@babel/plugin-proposal-object-rest-spread",
        {
          useBuiltIns: true
        }
      ],
      [
        "@babel/plugin-transform-runtime",
        {
          helpers: false,
          regenerator: true,
          corejs: false
        }
      ],
      [
        "@babel/plugin-transform-regenerator",
        {
          async: false
        }
      ],
      isProductionEnv && [
        "babel-plugin-transform-react-remove-prop-types",
        {
          removeImport: true
        }
      ]
    ].filter(Boolean)
  };
};
```

tsconfig.json
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "strictNullChecks": true
  },
  "exclude": ["**/*.spec.ts", "node_modules", "public"],
  "compileOnSave": false
}
```

**Comment by jorisre** [comment] 2020-11-05 18:05
@batamire Hi 👋🏻 

Does that error occur at build time ?

**Comment by sfederowicz** [comment] 2020-11-05 19:39
I'm running into that same runtime error (also using Rails + webpacker but no Typescript). I'm importing the yup resolver rather than the zod resolver, but it's the same error otherwise.

My Babel config is identical to the one posted above, excluding only the Typescript preset line (since we don't use Typescript):
 `['@babel/preset-typescript', { 'allExtensions': true, 'isTSX': true }]`

Issue occurs when using the `1.0.0` or `2.0.0-rc.1` version of the lib but didn't occur with the `0.1.1` or `0.2.0-beta.12`. 

Adding this plugin to Babel fixes the issue and prevents the runtime error from being thrown:
`@babel/plugin-transform-modules-commonjs`

Unfortunately, adding that plugin also causes a different runtime errors to be thrown for me in some Rails-related JS code (code that is unrelated to react-hook-form), so that alone likely won't be your panacea. Still trying to figure out how to get around this since I'm not great with webpack.

**Comment by batamire** [comment] 2020-11-05 21:33
It builds without problems, the error is pasted from Chrome Devtools, happens on component mount...
```
Uncaught ReferenceError: exports is not defined
```
Offending line:
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

@sfederowicz same thing happens with yup...

**Comment by studnik18** [comment] 2020-11-10 11:00
Up for yup...

**Comment by bluebill1049** [comment] 2020-11-16 21:38
Is this still an issue for everyone?

**Comment by studnik18** [comment] 2020-11-17 14:42
Yes. Can't update from 0.0.6 because of it. My most relevant dependencies:
`
"react": "^17.0.1",
"react-hook-form": "^6.11.0",
"@hookform/resolvers": "^0.0.6",
"yup": "^0.29.3",
"@rails/webpacker": "^5.2.1",
"react-on-rails": "^12.0.3"
`

**Comment by bluebill1049** [comment] 2020-11-17 22:10
@studnik18 have you try to upgrade to the latest?

**Comment by studnik18** [comment] 2020-11-18 10:33
Yes, I tried just before posting :) Our setting is quite complicated - it's a monorepo with rails 6 and webpacker as ruby gems, on the frontend side it's `@rails/webpacker 5.2.1` which features `webpack 4.x.x` according to the docs (no TypeScript).

**Comment by brentmulligan** [comment] 2020-12-04 21:42
Having the same issue, also using rails/webpacker. Downgrading to 0.1.1 did resolve.

**Comment by johnandresmedina** [comment] 2020-12-07 00:06
I was having the same issue, I tried to replicate it in codesandbox with no luck and after spending some more time it turned out to be a reference to the old way of importing the package: `@hookform/resolvers` instead of `@hookform/resolvers/yup`, so you might want to check all the references.

**Comment by studnik18** [comment] 2020-12-07 08:55
I had this lightbulb moment too :) But unfortunately that solution alone didn't help. Thanks anyway John.

**Comment by ramaboo** [comment] 2020-12-14 12:14
Getting this too for yup `import { yupResolver } from "@hookform/resolvers/yup";` on a Rails 6.1 project

**Comment by jorisre** [comment] 2020-12-14 13:07
Thanks for reporting, I'm looking for a solution

**Comment by YimingIsCOLD** [comment] 2020-12-23 22:03
I am getting this too for yup on a non-rails project. I am only getting the error on production build and not in development build.

**Comment by jorisre** [comment] 2020-12-31 08:10
Hi all, the last version 1.3.1 should fix this issue, someone can confirm ? Thanks

**Comment by amankkg** [comment] 2020-12-31 13:32
@jorisre 1.3.1 using snowpack on `import {zodResolver} from '@hookform/resolvers/zod` throws following error
```
SyntaxError: The requested module '../../web_modules/@hookform/resolvers/zod.js' does not provide an export named 'zodResolver'
```

**Comment by jorisre** [comment] 2020-12-31 13:36
@amankkg  thank for your feedbacks. Could you provide a snowpack example please ?

ℹ️  I'm working on resolvers v2 with a better module support

**Comment by amankkg** [comment] 2020-12-31 13:57
@jorisre hmm on 1.3.0 it works properly

here is my WIP https://github.com/amankkg/frontend-template

**Comment by amankkg** [comment] 2020-12-31 14:07
@jorisre it is quite messy 😅 let me know if you need clear and stable reproduction repo

**Comment by amankkg** [comment] 2021-01-05 07:12
My case is fixed with `1.4.0-beta.1`

**Comment by jorisre** [comment] 2021-01-05 13:05
@amankkg I'm glad it solves your problem ! :) But `1.4.0-beta.1` was a mistake with semantic-release. Please use `2.0.0-beta.3` instead.

For everyone which want to try the v2,  you can install the `@hookform/resolvers@beta`, at this time the `beta.3` contains:
- A TypeScript fix for Yup
- A better modules support _(without breaking changes)_

Feedbacks are really appreciated :) If some of you get some errors with **modules**, please reply here.

**Comment by tajdien** [comment] 2021-01-07 13:45
I had the same issue with `1.3.2` using snowpack. 
Upgrading it to `2.0.0-beta.3` resolved the issue for me aswell.

**Comment by MontoyaAndres** [comment] 2021-01-24 22:26
I'm facing the same issue as https://github.com/react-hook-form/resolvers/issues/100 , 

```
andres@andres:~/Entrepreneurship/TeVi$ yarn build

yarn run v1.22.10
$ next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
info  - Using external babel configuration from /home/andres/Entrepreneurship/TeVi/.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
/home/andres/Entrepreneurship/TeVi/node_modules/@hookform/resolvers/dist/yup.js:2
import { transformToNestObject } from 'react-hook-form';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/andres/Entrepreneurship/TeVi/node_modules/@hookform/resolvers/yup.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Now, I can't deploy to vercel :(

**Comment by MontoyaAndres** [comment] 2021-01-24 22:33
Also, I updated to "@hookform/resolvers": "1.3.2" and I get the same error...

**Comment by bluebill1049** [comment] 2021-01-24 22:35
@MontoyaAndres try to use the latest beta version.

**Comment by MontoyaAndres** [comment] 2021-01-24 22:38
@bluebill1049 Works great! Thank you so much! I was deploying normally to Vercel when that error appears surprisingly 🤔🤔🤔.

**Comment by bluebill1049** [comment] 2021-01-24 22:40
> @bluebill1049 Works great! Thank you so much! I was deploying normally to Vercel when that error appears surprisingly 🤔🤔🤔.

not sure about that :( sounds like picking update the latest, but your package.json says another story. (pick up the latest patch)

**Comment by MontoyaAndres** [comment] 2021-01-24 22:42
Very strange, I didn't update anything in my code about react-hook-form... Just appeared when the building was executing in Vercel :(

**Comment by asotog** [comment] 2021-01-27 14:17
> @amankkg I'm glad it solves your problem ! :) But `1.4.0-beta.1` was a mistake with semantic-release. Please use `2.0.0-beta.3` instead.
> 
> Next.js's users have the same problem since 1.3.1 : #100
> Workaround possible: use the [v1.3.0](https://github.com/react-hook-form/resolvers/issues/100#issuecomment-752883002) or try the v2 beta
> 
> For everyone which want to try the v2, you can install the `@hookform/resolvers@beta`, at this time the `beta.3` contains:
> 
> * A TypeScript fix for Yup
> * A better modules support _(without breaking changes)_
> 
> Feedbacks are really appreciated :) If some of you get some errors with **modules**, please reply here.

This worked for me, thanx, when are you planning to release this version?

**Comment by jorisre** [comment] 2021-01-27 14:19
@asotog  At the same time of react-hook-form v7

**Comment by bluebill1049** [comment] 2021-01-27 21:39
> @asotog At the same time of react-hook-form v7
> 
> @bluebill1049 Do we have a "deadline" ?

No, we don't. It's open-source, we are all working on this in our free time. So no pressure, we get it right and we ship it out. I am planning to do a quick video to cover some of the major changes and improvements, then we can release a beta version and get more users to "test" this out.

**Comment by borivojevic** [comment] 2021-01-30 18:23
I had the same issue with 1.3.2 using snowpack. 2.0.0-beta.3 didn't work either.

Although snowpack suggests [this workaround](https://www.snowpack.dev/reference/common-error-details#uncaught-syntaxerror%3A-the-requested-module-%E2%80%98%2F_snowpack%2Fpkg%2Fxxxxxx.js%E2%80%99-does-not-provide-an-export-named-%E2%80%98yyyyyy%E2%80%99) that seems to be working for me:

```tsx
// doesn't work
import type { yupResolver } from '@hookform/resolvers/yup';

// it works
import { yupResolver } from '@hookform/resolvers/yup';
```

**Comment by borivojevic** [comment] 2021-01-31 13:23
Another workaround that works with snowpack v3.0.11 would be:

```tsx
import hookforResolvers from '@hookform/resolvers/yup';
const yupResolver = hookforResolvers.yupResolver;
```

**Comment by bluebill1049** [comment] 2021-01-31 22:22
@jorisre any idea on this one above?

**Comment by jorisre** [comment] 2021-02-01 10:31
It seems to work for @tajdien, can you share a working example please ?

@borivojevic I'm not familiar with Skypack but if you have a reproductible example to provide then I can investigate thanks !

**Comment by borivojevic** [comment] 2021-02-01 10:57
@jorisre I hope [this example](https://github.com/borivojevic/create-snowpack-app) helps.

`yarn install && yarn start` should result in error.

[This](https://github.com/borivojevic/create-snowpack-app/commit/3343359f5f048c09b650fe1c9804b9ce71aef5df#diff-49c318d204c7d0caa09e6b1dcec4392a2436fc8f02768220cdbe2de8f364b723) is the implementation that's problematic.

**Comment by jorisre** [comment] 2021-02-01 11:13
@borivojevic Happy to try Skypack, esbuild is fast as expected 🚀 

In your example you use the version 1.3.3 which have an issue with module exports _(solved in v2)_.
In your case, I recommend to use the 1.3.0 or try the [v2 beta.](https://github.com/react-hook-form/resolvers/releases)
I get your example working with these both versions.

I added a note for Snowpack users : https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998

Hope it helps

**Comment by borivojevic** [comment] 2021-02-01 11:22
Thanks @jorisre. I can confirm that v2 beta works on this smaller example as well.

**Comment by WorldOfMaze** [comment] 2021-02-04 02:46
I was having this issue with yup and nextjs.  After downgrading to 1.3.0, everything seems to be working OK.  Thanks for the workaround @jorisre

**Comment by hamzahasbi** [comment] 2021-02-28 18:50
using  "@hookform/resolvers": "2.0.0-beta.3" with  "next": "10.0.7" seems to work perfectly!
Thanks !

**Comment by k-maekawa** [comment] 2021-03-02 07:04
> 2.0.0-beta.3
@hamzahasbi 
It works well for me, thanks.

**Comment by javierfuentesm** [comment] 2021-03-12 05:30
> @amankkg I'm glad it solves your problem ! :) But `1.4.0-beta.1` was a mistake with semantic-release. Please use `2.0.0-beta.3` instead.
> 
> Next.js's users have the same problem since 1.3.1 : #100
> Workaround possible: use the [v1.3.0](https://github.com/react-hook-form/resolvers/issues/100#issuecomment-752883002) or try the v2 beta
> 
> **EDIT (2/1/2020):** Same for Snowpack users
> 
> For everyone which want to try the v2, you can install the `@hookform/resolvers@beta`, at this time the `beta.3` contains:
> 
> * A TypeScript fix for Yup
> * A better modules support _(without breaking changes)_
> 
> Feedbacks are really appreciated :) If some of you get some errors with **modules**, please reply here.

It didnt work for me 
![image](https://user-images.githubusercontent.com/19244527/110896658-a85e8d80-82c1-11eb-8ee0-ddead121ca31.png)

![image](https://user-images.githubusercontent.com/19244527/110896676-b1e7f580-82c1-11eb-8a45-72f22db0ea2f.png)

**Comment by javierfuentesm** [comment] 2021-03-12 05:32
> > using "@hookform/resolvers": "2.0.0-beta.3" with "next": "10.0.7" seems to work perfectly!
> 
> @hamzahasbi
> It works well for me, thanks.

For me too !! :D

**Comment by 72636c** [comment] 2021-03-12 06:46
`^1.3.0` will install the latest version `>=1.3.0 <2.0.0`. If you want to pin a specific version you should remove the caret `^`.

**Comment by iltonbarbosa** [comment] 2021-03-17 15:35
I have the same problem:

exports.__esModule = true;
^

ReferenceError: exports is not defined

**Comment by jorisre** [comment] 2021-03-26 14:36
👋🏻 
You can try the last version [v1.3.6](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.6). The issue should be solved

**Closed** 2021-03-28 09:46 UTC
Labels: bug

**Comment by decebal** [comment] 2021-09-09 22:39
1.3.9 seems to have the same issue again :(

**Comment by studnik18** [comment] 2021-09-10 10:26
There is 2.8.0 released. Why would you bother with 1.3.9 ?

**Comment by decebal** [comment] 2021-09-10 12:59
thanks @studnik18 🙈 👍🏽
