### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ivanafanasyev** [react-hook-form/resolvers#111] opened 2021-01-06 10:30 UTC
<img width="1191" alt="Screenshot 2021-01-06 at 13 30 06" src="https://user-images.githubusercontent.com/25664253/103758464-4c5a5d00-5023-11eb-9f21-62586004c3e8.png">
Next.js

```tsx
import { yupResolver } from '@hookform/resolvers/yup';

import AuthLayout from '../../../layouts/AuthLayout';
import { LoginInputs, LoginSchema } from './types';

const LoginPage: FC = (): JSX.Element => {
	const { register, handleSubmit } = useForm<LoginInputs>({
		resolver: yupResolver(LoginSchema),
	});
```

**Comment by jorisre** [comment] 2021-01-06 10:38
Thanks for reporting

Duplicate of https://github.com/react-hook-form/resolvers/issues/100

Problem solved in V2 currently in beta, more detail here: https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998

**Closed by jorisre** 2021-01-06 10:38 UTC
