### ISSUE TITLE
Type problems after update resolver to 1.3.0

### ISSUE THREAD

**Issue by william-hotmart** [react-hook-form/resolvers#97] opened 2020-12-30 18:36 UTC
After update @hookform/resolvers to the version 1.3.0, this code above no longer works.

The TS compiler points out the error:

```
Type 'Resolver<AssertsShape<Assign<Record<string, AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>>, { title: RequiredStringSchema<string, Record<string, any>>; buttonTitle: RequiredStringSchema<...>; exibitionMode: RequiredStringSchema<...>; link: RequiredStringSchema<...>; duration: NumberSchema<...>; }>>,...' is not assignable to type 'Resolver<FormData, object>'.
  Types of parameters 'values' and 'values' are incompatible.
    Type 'FormData' is not assignable to type '{ [x: string]: never; title: string; buttonTitle: string; exibitionMode: string; link: string; duration: number; }'.
      Index signature is missing in type 'FormData'.ts(2322)
form.d.ts(39, 5): The expected type comes from property 'resolver' which is declared here on type 'Partial<{ mode: "onBlur" | "onChange" | "onSubmit" | "onTouched"
```

If I comment the lines of _exibitionMode_ and _colorBackground_ the error disappears.

This is the code that I'm working with

```js
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import { object, string, number } from 'yup'

enum Color {
  DARK = 'dark',
  LIGHT = 'light',
  PURPLE = 'purple',
  ORANGE = 'orange',
  RED = 'red',
  GREEN = 'green'
}

enum ExibitionMode {
  INFINITY = 'infinity',
  LIMITED = 'limited'
}

interface FormData {
  title: string,
  buttonTitle: string,
  exibitionMode: ExibitionMode,
  link: string,
  duration: number,
  colorBackground: Color
}

const TITLE_MAX_LENGTH = 96
const BUTTON_TITLE_MAX_LENGTH = 28

const schema = object().shape({
  title: string().max(TITLE_MAX_LENGTH).required(),
  buttonTitle: string().max(BUTTON_TITLE_MAX_LENGTH).required(),
  exibitionMode: string().required(),
  link: string().required().url(),
  duration: number().when('exibitionMode', (exibitionMode, schema) => {
    return exibitionMode === ExibitionMode.LIMITED ? schema.min(1).required() : schema
  })
})

const Test = () => {
  const { register, handleSubmit } = useForm<FormData>({
    resolver: yupResolver(schema),
    mode: 'onBlur'
  })
}
```

**Comment by jorisre** [comment] 2020-12-30 18:40
👋🏻  Hi
Which version of Yup are you using ?

Can you provide a reproduction in a [codesandbox](https://codesandbox.io/) please ? thx

**Comment by william-hotmart** [comment] 2020-12-30 20:13
I forgot. Sorry!
`"yup": 0.32.8"` and `"react-hook-form: 6.13.1"`

**Comment by jorisre** [comment] 2020-12-30 21:52
Thanks!

You get this error because your `FormData` contains more properties than your schema. 
```ts
type MySchema = yup.InferType<typeof schema>;
```

You can see `MySchema` and `FormData` are different, that's why you get that error.

You've a second TS error because you're using TypeScript enum but `yup.InferType` could return an enum:

```ts
const schema = object({
  exibitionMode: string().oneOf(["infinity", "limited"]).required(),
});

type Schema = InferType<typeof schema>;
// Schema['exibitionMode'] = string instead of 'infinity' | 'limited'
```

**Comment by william-hotmart** [comment] 2020-12-31 02:51
- So should all the values in `FormData` also be in the schema? If my form contain a value that I do not need to validate (like `colorBackground`), how to proceed?
- Can't I use TS enum as a type in the `useForm` generic interface?

**Comment by jorisre** [comment] 2020-12-31 17:40
1. Yes, at this time, all values in `FormData` should be in the schema
2. TS enum is a limitation of yup, `InferType` of yup could return a TS enum

**Comment by william-hotmart** [comment] 2020-12-31 18:48
I don't know why but with version 1.2.0 I'm not seeing those problems.
Well, thanks @jorisre, you were very kind!

**Comment by jorisre** [comment] 2020-12-31 19:03
@william-hotmart with version 1.2.0, types was wrong see above ⬇️ 

It returns multiples `Record<string, any>`
![Screen Shot 2020-12-31 at 19 59 39](https://user-images.githubusercontent.com/7545547/103422679-f3ae3e80-4ba2-11eb-8300-760abc7dd2cf.png)


With 1.3.0
![Screen Shot 2020-12-31 at 20 00 14](https://user-images.githubusercontent.com/7545547/103422698-0aed2c00-4ba3-11eb-9d2b-05c190f72cc3.png)

**Comment by william-hotmart** [comment] 2020-12-31 23:00
Yeah, I see!
So returning to this question: 
`If my form contain a value that I do not need to validate (like colorBackground), how to proceed?'

Do I just put it in the schema like `colorBackground: string()`?

**Comment by jorisre** [comment] 2020-12-31 23:26
Yes you can as a workaround solution

**Comment by william-hotmart** [comment] 2020-12-31 23:28
Ok! Thanks :smile:

**Comment by vtrphan** [comment] 2021-01-04 12:31
i have some type errors too, and after fixing some of it i ended up having this error which i don't know how to solve:
`Typescript: Index signature is missing in type
`
Problem occurred after updating to > 1.3.0

**Comment by jorisre** [comment] 2021-01-04 12:39
@vtrphan could you provide a codesandbox please ?

**Comment by vtrphan** [comment] 2021-01-04 13:10
i can't quite reproduce it in codeandsandbox, but i have included the schema definitions in a small snippet, and below is one of the errors i got:
`Type 'Resolver<AssertsShape<Assign<Record<string, AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>>, { salutation: RequiredStringSchema<string, Record<string, any>>; ... 20 more ...; concentrator: BooleanSchema<...>; }>>, object>' is not assignable to type 'Resolver<IFormInputs, object>'.
  Types of parameters 'values' and 'values' are incompatible.
    Type 'IFormInputs' is not assignable to type '{ [x: string]: never; salutation: string; firstName: string; lastName: string; companyName: string; address: { [x: string]: never; street: string; addressComplement: string; zip: string; city: string; country: string; }; ... 16 more ...; concentrator: boolean | undefined; }'.
      Types of property 'address' are incompatible.
        Type '{ street: string; addressComplement: string; zip: string; city: string; country: string; }' is not assignable to type '{ [x: string]: never; street: string; addressComplement: string; zip: string; city: string; country: string; }'.
          Property 'street' is incompatible with index signature.
            Type 'string' is not assignable to type 'never'.  TS2322`

Schema definition: https://codesandbox.io/s/testhookformresolvers-meelj

**Comment by seifsg** [comment] 2021-01-04 16:01
@jorisre I'm facing same problem as @vtrphan I think this is an issue with type definition. This happened just right after the update.
Here is a sample of my code:
```typescript
const schema = yup.object().shape({
  email: yup
    .string()
    .email('Please enter a valid email address')
    .required('Please enter your email.'),
  password: yup
    .string()
    .required('Please enter your password.')
    .min(6, 'Password is too short!')
    .max(40, 'Password is too long!'),
  role: yup
    .string()
    .required('Please select a role.')
    .nullable(),
});
interface FormInterface {
  email: string;
  password: string;
  role: string;
}
const LoginForm = React.memo((props: LoginFormProps) => {

  const { control, handleSubmit, errors } = useForm<FormInterface>({
    resolver: yupResolver(schema),
  });```
![image](https://user-images.githubusercontent.com/6075316/103553792-3c6d3c80-4eae-11eb-8f53-d7ccf87cc41f.png)

Error: 
`
Type 'Resolver<AssertsShape<Assign<Record<string, AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>>, { email: RequiredStringSchema<string | undefined, Record<string, any>>; password: RequiredStringSchema<...>; role: any; }>>, object>' is not assignable to type 'Resolver<FormInterface, object>'.
  Types of parameters 'values' and 'values' are incompatible.
    Type 'FormInterface' is not assignable to type '{ [x: string]: never; email: string; password: string; role: any; }'.
      Index signature is missing in type 'FormInterface'.ts(2322)
`

**Comment by jorisre** [comment] 2021-01-04 16:10
@seifsg Thanks for reporting. I'll fix it tonight

**Comment by vtrphan** [comment] 2021-01-04 16:14
@seifsg thanks for reporting

**Comment by jorisre** [comment] 2021-01-04 22:08
Fixed in [1.3.2](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.2).

Any feedbacks is appreciated :)

**Comment by Ulydev** [comment] 2021-01-04 22:23
What a coincidence, I just encountered this exact same issue on a new project, 30 minutes ago. Thank you for your quick response! 💪

**Comment by mrlubos** [comment] 2021-01-05 15:34
Hey! I had the same issue and can confirm it's now fixed. However, I am seeing this error message when running unit tests.

```
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/runner/work/webapp/webapp/node_modules/@hookform/resolvers/dist/yup.js:2
    import { transformToNestObject } from 'react-hook-form';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@hookform/resolvers/yup.js:1:107)
```

Has something else changed since `1.3.0`? Until then everything worked fine, this happens with `1.3.2`.

**Comment by william-hotmart** [comment] 2021-01-05 16:10
@mrlubos My solution to this problem was to the code below in my jest.config file

```
 "transformIgnorePatterns": [
    '/node_modules/(?!@hookform/*).+\\.[t|j]sx?$'
  ],
```

I don't know if is right, but it worked

**Comment by mrlubos** [comment] 2021-01-06 04:47
@william-hotmart @jorisre Thanks both! Will this new configuration be necessary in v2?

**Comment by ljharb** [comment] 2021-03-25 05:47
@jorisre the implication is that you made a breaking change, albeit unintentional, in a minor version, and that you're not planning to fix it in the v1 line. Can you confirm?

(semver would dictate that you revert back to v1.2.x and publish it as a v1.3 latest, at the very least)

**Comment by jorisre** [comment] 2021-03-25 14:12
Hi @ljharb 👋🏻 

If we revert back to v1.2.x a new problem will occur for users which use webpacker.
Possible work around: https://github.com/react-hook-form/resolvers/issues/71#issuecomment-754623998

The V2 fix all of these issues. We are running the V2 beta since months with success, I think we can apply the same fix on the version 1. I keep an eye on this issue and I'll fix V1 on the weekend

As a reminder:
- Starting at [Resolvers@v2.0.0-beta.7](https://github.com/react-hook-form/resolvers/releases/tag/v2.0.0-beta.7),React Hook Form V7 is required
- We'll continue to support the resolvers v1 for React Hook Form v6

**Comment by jorisre** [comment] 2021-03-26 14:35
👋🏻 
You can try the last version [v1.3.6](https://github.com/react-hook-form/resolvers/releases/tag/v1.3.6). The issue should be solved

**Closed** 2021-03-28 09:46 UTC
Labels: bug

**Comment by jorisre** [comment] 2021-09-21 05:11
> I am getting this error in 2.8.1 again. 2.8.0 is fine.

Can you open a new issue with a reproductible example please?

**Comment by andreisocaciu** [comment] 2021-09-27 15:12
Reproductible example here:
https://codesandbox.io/s/https-github-com-react-hook-form-resolvers-issues-97-vpk5w?file=/src/App.tsx

**Comment by castrogh** [comment] 2022-07-26 16:01
Hello!

I'm facing something like this.

Error Message: Type 'Control<FormData, object>' cannot be assigned to type 'Control<any, any>'.

`import React from 'react';
import { Button } from '../Button';
import { ControlledInput } from '../ControlledInput';
import { Container } from './styles';
import { useForm } from 'react-hook-form';
import * as yup from "yup";
import { yupResolver } from '@hookform/resolvers/yup';


type FormData = {
  name: string;
  email: string;
  password: string;
  password_confirm: string;
}

const schema = yup.object({
  name: yup.string().required("Informe o seu nome"),
  email: yup.string().email("E-mail inválido").required("Informe o e-mail"),
  password: yup.string().min(8, "A senha deve ter, no mínimo, 8 dígitos").required("Informe a senha"),
  password_confirm: yup.string().oneOf([yup.ref('password'), null], 'A senha de confirmação não é a mesma digitada no campo "Senha"').required("Digite a confirmação da senha")
});

export function Form() {
  const { control, handleSubmit, formState:{ errors } } = useForm<FormData>({
    resolver: yupResolver(schema)
  });

  function handleUserRegister(data: FormData) {
    console.log(data);

  }

  return (
    <Container>
      <ControlledInput
        name="name"
        **control**={control} // Error Message: Type 'Control<FormData, object>' cannot be assigned to type 'Control<any, any>'.
        icon="user"
        placeholder="Digite seu nome"
        placeholderTextColor = 'lightblue'
        error={errors.name}
      />
      <ControlledInput
        name="email"
        **control**={control} // Error Message: Type 'Control<FormData, object>' cannot be assigned to type 'Control<any, any>'.
        icon="mail"
        placeholder="Digite seu e-mail"
        placeholderTextColor = 'lightblue'
        keyboardType="email-address"
        autoCapitalize='none'
        error={errors.email}
      />
      <ControlledInput
        name="password"
        **control**={control} // Error Message: Type 'Control<FormData, object>' cannot be assigned to type 'Control<any, any>'.
        icon="lock"
        placeholder="Digite sua senha"
        placeholderTextColor = 'lightblue'
        secureTextEntry
        error={errors.password}
      />
      <ControlledInput
        name="password_confirm"
        **control**={control} // Error Message: Type 'Control<FormData, object>' cannot be assigned to type 'Control<any, any>'.
        icon="lock"
        placeholder="Confirme sua senha"
        placeholderTextColor = 'lightblue'
        secureTextEntry
        error={errors.password_confirm}
      />

      <Button
        title="Cadastrar"
        onPress={handleSubmit(handleUserRegister)}
      />
    </Container>
  )
}`

Below you can see the index page, where I created the type Props:
I don't know wich type I need to set in control

`import React from 'react';
import { Control, Controller, FieldError } from 'react-hook-form';
import { Input, InputProps } from '../Input';

type Props = InputProps & {
    **control: Control<any>;**
    name: string;
    error?: FieldError;
}

import { Error } from './style';

export function ControlledInput({ control, name, error, ...rest }: Props){
    return(
        <>
    <Controller
    name = {name}
    control={control}
    render = {({field: {onChange, value}}) => (
        <Input
        onChangeText={onChange}
        value={value} 
        {...rest }
        />
    )}
    />

    {
        error && <Error>{error.message}</Error>
    }

    </>
    )
}`

**Comment by amanzrx4** [comment] 2023-01-24 18:41
I'm also getting a similar error while working with material UI and RHF useController. 
```const Test = () => {
  const testSchema = yup.object({
    test: yup.string().required("Required"),
  });

  type TestInputs = yup.InferType<typeof testSchema>;

  const INITIAL_VALUES = {
    test: "",
  };

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    reset,
    getValues,
    control,
    formState: { errors, isDirty, isSubmitting },
  } = useForm<TestInputs>({
    mode: "onSubmit",
    reValidateMode: "onChange",
    defaultValues: INITIAL_VALUES,
    resolver: yupResolver(testSchema),
    context: undefined,
    criteriaMode: "firstError",
    shouldFocusError: true,
    shouldUnregister: false,
    delayError: undefined,
  });

  return (
    <Box>
      <form>
        <ControlledTextField
          type="text"
          placeholder="Test"
          defaultValue={INITIAL_VALUES.test}
          control={control}  // shows an error
        />
      </form>
    </Box>
  );
};```


The Error : ```Type 'Control<AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }>, any>' is not assignable to type 'Control<FieldValues, any>'.
  Types of property '_reset' are incompatible.
    Type 'UseFormReset<AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }>>' is not assignable to type 'UseFormReset<FieldValues>'.
      Types of parameters 'values' and 'values' are incompatible.
        Type 'FieldValues | { [x: string]: any; } | ResetAction<FieldValues> | undefined' is not assignable to type 'AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }> | { test?: string | undefined; } | ResetAction<AssertsShape<{ test: RequiredStringSchema<...>; }>> | undefined'.
          Type 'ResetAction<FieldValues>' is not assignable to type 'AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }> | { test?: string | undefined; } | ResetAction<AssertsShape<{ test: RequiredStringSchema<...>; }>> | undefined'.
            Type 'ResetAction<FieldValues>' is not assignable to type 'ResetAction<AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }>>'.
              Type 'FieldValues' is not assignable to type 'AssertsShape<{ test: RequiredStringSchema<string | undefined, AnyObject>; }>'.ts(2322)
TextField.tsx(39, 3): The expected type comes from property 'control' which is declared here on type 'IntrinsicAttributes & ControlledTextFieldProps'```

**Comment by kleenkanteen** [comment] 2024-01-07 23:48
> I'm also getting a similar error while working with material UI and RHF useController.

Same. My error message:

`Type 'Resolver<{ email?: string | undefined; password: string; }, any>' is not assignable to type 'Resolver<IFormInputs, any>'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'ResolverOptions<IFormInputs>' is not assignable to type 'ResolverOptions<{ email?: string | undefined; password: string; }>'.
      Type '{ email?: string | undefined; password: string; }' is not assignable to type 'IFormInputs'.ts(2322)`

Code:

```ts
import type { FC } from 'react';
import { yupResolver } from '@hookform/resolvers/yup';
import { TextField } from '@mui/material';
import Head from 'next/head';
import { useForm, Controller } from 'react-hook-form';
import type { SubmitHandler } from 'react-hook-form';
import * as yup from 'yup';

interface IFormInputs {
  email: string;
  password: string;
}

const schema = yup.object().shape({
  email: yup.string().email(),
  password: yup.string().min(4).max(20).required(),
});

const Home: FC = () => {
  const {
    register,
    control, 
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<IFormInputs>({
    resolver: yupResolver(schema),
  });

  const onSubmit: SubmitHandler<IFormInputs> = (data) => console.log('data submitted: ', data);

  console.log(watch('email'));
  console.log('errors are', errors);

  return (
    <div>
      <Head>
        <title>ReceitaClient</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Controller
            name="email"
            control={control}
            defaultValue="example@dev.com"
            render={({ field }) => (
              <TextField
                {...field}
                label="Email"
                variant="outlined"
                error={!!errors.email}
                helperText={errors.email ? errors.email?.message : ''}
                fullWidth
                margin="dense"
              />
            )}
          />
          <br />
          <Controller
            name="password"
            control={control}
            defaultValue=""
            render={({ field }) => (
              <TextField
                {...field}
                type="password"
                label="Password"
                variant="outlined"
                error={!!errors.password}
                helperText={errors.password ? errors.password?.message : ''}
                fullWidth
                margin="dense"
              />
            )}
          />
          <input type="submit" />
        </form>
      </main>
    </div>
  );
};

export default Home;
```
